{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import pickle\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.base import BaseEstimator, TransformerMixin\n",
    "\n",
    "# The custom scaler class\n",
    "class CustomScaler(BaseEstimator,TransformerMixin):\n",
    "    \n",
    "    def __init__(self,columns,copy = True, wiyh_mean = True, with_std = True):\n",
    "        self.scaler = StandardScaler(copy,with_mean,with_std)\n",
    "        self.columns = columns\n",
    "        self.mean_ = None\n",
    "        self.var_ = None\n",
    "        \n",
    "    def fit(self,X,y = None):\n",
    "        self.scaler.fit(X[self.columns],y)\n",
    "        self.mean_ = np.array(np.mean(X[self.columns]))\n",
    "        self.var_ = np.array(np.var(X[self.columns]))\n",
    "        return self\n",
    "    \n",
    "    def transform(self, X, y = None, copy = None):\n",
    "        init_col_order = X.columns\n",
    "        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),columns = self.columns)\n",
    "        X_not_scaled =X.loc[:,~X.columns.isin(self.columns)]\n",
    "        return pd.concat([X_not_scaled,X_scaled],axis = 1)[init_col_order]\n",
    "    \n",
    "# Create special class that we are going to use from here to predict new data\n",
    "\n",
    "class absenteeism_model():\n",
    "    \n",
    "    def __init__(self,model_file,scaler_file):\n",
    "        \n",
    "        with open('model','rb') as model_file, open('scaler','rb') as scaler_file:\n",
    "            self.reg = pickle.load(model_file)\n",
    "            self.scaler = pickle.load(scaler_file)\n",
    "            self.data = None\n",
    "            \n",
    "    def load_and_clean_data(self,data_file):\n",
    "        \n",
    "        df = pd.read_csv(data_file,delimiter = ',')\n",
    "        \n",
    "        #store the data in new variable for later use\n",
    "        self.df_with_predictions = df.copy()\n",
    "        \n",
    "        #drop the 'ID' column\n",
    "        df = df.drop(['ID'],axis = 1)\n",
    "        \n",
    "        # to preserve the code we have created inprevious section ,we will add the column with NAN string\n",
    "        df['Absenteeism Time in Hours'] = 'NaN'\n",
    "        \n",
    "        #create separate dataframe to create a dummy variable\n",
    "        reason_columns = pd.get_dummies(df['Reason for Absense'])\n",
    "        \n",
    "        #split reason column into 4 types\n",
    "        reason_type_1 = reason_columns.loc[:,1:14].max(axis = 1)\n",
    "        reason_type_2 = reason_columns.loc[:,15:17].max(axis = 1)\n",
    "        reason_type_3 = reason_columns.loc[:,18:21].max(axis = 1)\n",
    "        reason_type_4 = reason_columns.loc[:,22:].max(axis = 1)\n",
    "        \n",
    "        #drop 'Reason for ABSENCE' to avoid multicollinearity\n",
    "        df = df.drop(['Reason for Absence'],axis = 1)\n",
    "        \n",
    "        #concatenate df and 4 types\n",
    "        df = pd.concat([df,reason_type_1,reason_type_2,reason_type_3,reason_type_4],axis = 1)\n",
    "        \n",
    "        #Assign Names to 4 Types\n",
    "        column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',\n",
    "       'Daily Work Load Average', 'Body Mass Index', 'Education',\n",
    "       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']\n",
    "        \n",
    "        df.columns = column_names\n",
    "        \n",
    "        # Reorder the columns in df\n",
    "        column_names_reordered = [ 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Date', 'Transportation Expense', 'Distance to Work', 'Age',\n",
    "       'Daily Work Load Average', 'Body Mass Index', 'Education',\n",
    "       'Children', 'Pets', 'Absenteeism Time in Hours']\n",
    "        \n",
    "        df = df[column_names_reordered]\n",
    "        \n",
    "        # Convert 'date' to datetime \n",
    "        df['Date'] = pd.to_datetime(df['Date'],format = '%d/%m/%Y')\n",
    "        \n",
    "        # Create a list with month Values\n",
    "        list_month = []\n",
    "        \n",
    "        for i in range(df.shape[0]):\n",
    "            list_month.append(df['Date'][i].month)\n",
    "        \n",
    "        df['Month Value'] = list_month\n",
    "        \n",
    "        # Createlist with 'day of the week'\n",
    "        def date_to_weekday(date_value):\n",
    "            return date_value.weekday()\n",
    "        \n",
    "        df['Day of the week'] = df['Date'].apply(date_to_weekday)\n",
    "        \n",
    "        #drop date column\n",
    "        df = df.drop(['Date'],axis = 1)\n",
    "        \n",
    "        # Reorder the columns names\n",
    "        column_names_updated = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value','Day of the week',\n",
    "       'Transportation Expense', 'Distance to Work', 'Age',\n",
    "       'Daily Work Load Average', 'Body Mass Index', 'Education',\n",
    "       'Children', 'Pets', 'Absenteeism Time in Hours']\n",
    "        \n",
    "        df = df[column_names_updated]\n",
    "        \n",
    "        #map Education into dummy\n",
    "        df['Education'] = df['Education'].map({1:0,2:1,3:1,4:1})\n",
    "        \n",
    "        # replace the NaNValues\n",
    "        df = df.fillna(value = 0)\n",
    "        \n",
    "        # drop the original Absenteeism time \n",
    "        df = df.drop(['Absenteeism Time in Hours'],axis = 1)\n",
    "        \n",
    "        #drop the variables we decided we dont need\n",
    "        df = df.drop(['Day of the week', 'Distance to Work', 'Daily Work Load Average'],axis = 1)\n",
    "        \n",
    "        #checkpoint\n",
    "        self.preprocessed_data = df.copy()\n",
    "        \n",
    "        # we need this line so we can use it in next function\n",
    "        self.data = self.scalar.transform(df)\n",
    "        \n",
    "    # A function which outputs the probability of data to be 1\n",
    "    def predicted_probability(self):\n",
    "        if(self.data is not None):\n",
    "            pred = self.reg.predict_proba(self.data)[:,1]\n",
    "            return pred\n",
    "        \n",
    "    # A function which outputs 0 or 1 \n",
    "    def predicted_output_category(self):\n",
    "        if(self.data is not None):\n",
    "            pred_outputs = self.reg.predict(self.data)\n",
    "            return pred_outputs\n",
    "    \n",
    "    # Predict the outputs and probabilities and \n",
    "    # add column with these values at the end of the data\n",
    "    def predicted_outputs(self):\n",
    "        if(self.data is not None):\n",
    "            self.preprocessed_data['Probability'] = self.reg.predict_proba(self.data)[:,1]\n",
    "            self.preprocessed_data['Prediction'] = self.reg.predict(self.data)\n",
    "            return self.preprocessed_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
